### ISSUE TITLE
Error in home bridge.log "Error getting power state: TypeError: callback is not a function"

### ISSUE THREAD

**Issue by morkjt** [lukepistrol/homebridge-magichome-accessory#2]
I get an error that hangs home bridge permanently when trying to connect to the exact same controller shown on the home page:

[10/6/2022, 9:15:07 AM] [MagicHome] [Heart] Error getting power state: TypeError: callback is not a function
    at /usr/local/lib/node_modules/homebridge-magichome-accessory/src/MHControl.ts:321:9
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:533:9)
    at processTimers (node:internal/timers:507:7)
[10/6/2022, 9:15:07 AM] [MagicHome] [Heart] Error getting brightness: TypeError: callback is not a function
    at /usr/local/lib/node_modules/homebridge-magichome-accessory/src/MHControl.ts:321:9

Here is my config.json extract:

	{
            "name": "MagicHome",
	    "devices": [
      		{
                    "name": "Heart",
                    "ip": "192.168.50.12",
	 	    "port": 5577,
                    "dimmable": true
                }
            ],
	    "connect_timeout": 1000,
            "response_timeout": 500,
            "command_timeout": 100,
            "platform": "MagicHomePlatform"
	}

**Comment by joshjohanning** [comment]
Same!

**Comment by ThomasFarrenkopf** [comment]
Same with latest version 1.0.3:

[19.1.2023, 14:37:01] [MagicHome] [Living] Error getting power state: TypeError: callback is not a function
    at /var/lib/homebridge/node_modules/homebridge-magichome-accessory/src/MHControl.ts:321:9
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[19.1.2023, 14:37:01] [MagicHome] [Living] Error getting brightness: TypeError: callback is not a function
    at /var/lib/homebridge/node_modules/homebridge-magichome-accessory/src/MHControl.ts:321:9
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

My configuration:
    "name": "MagicHome",
            "devices": [
                {
                    "name": "Living",
                    "ip": "192.168.XXX.XXX",
                    "port": 5577,
                    "dimmable": true
                }
            ],
            "connect_timeout": 1000,
            "response_timeout": 500,
            "command_timeout": 100,
            "platform": "MagicHomePlatform"
        }
